package com.exshell.ops.activity.enums;

import com.google.common.base.CaseFormat;
import com.exshell.base.ErrorCode;

public enum AccountErrorEnum implements ErrorCode {

  // 账户余额不足，不区分动作类型
  ACCOUNT_BALANCE_INSUFFICIENT_ERROR,

  ACCOUNT_CREATE_ACCOUNT_ERROR,

  ACCOUNT_TYPE_ERROR,

  // 乐观锁导致的资产变更错误
  // 账户余额增加失败
  ACCOUNT_SUBACCOUNT_INCREASE_BALANCE_ERROR,

  // 账户余额增加多次失败
  ACCOUNT_SUBACCOUNT_INCREASE_BALANCE_MULTIPLE_ERROR,

  // 账户余额减少失败
  ACCOUNT_SUBACCOUNT_DECREASE_BALANCE_ERROR,

  // 账户余额减少多次失败
  ACCOUNT_SUBACCOUNT_DECREASE_BALANCE_MULTIPLE_ERROR,

  // 账户余额更新失败
  ACCOUNT_SUBACCOUNT_UPDATE_ERROR,

  // 系统上账
  ACCOUNT_SYSTEMIN_ACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_SYSTEMIN_ACCOUNT_TYPE_UNSUPPORT_ERROR,

  ACCOUNT_SYSTEMIN_SYSTEM_SUBACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_SYSTEMIN_SOURCE_ID_DUPLICATE_ERROR,

  ACCOUNT_SYSTEMIN_SOURCE_TYPE_UNSUPPORT_ERROR,

  // 转账

  ACCOUNT_TRANSFER_NEGATIVE_AMOUNT_ERROR,

  ACCOUNT_TRANSFER_FROM_ACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_TRANSFER_SOURCE_TYPE_UNSUPPORT_ERROR,

  ACCOUNT_TRANSFER_FROM_ACCOUNT_TYPE_UNSUPPORT_ERROR,

  ACCOUNT_TRANSFER_TO_ACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_TRANSFER_TO_ACCOUNT_TYPE_UNSUPPORT_ERROR,

  ACCOUNT_TRANSFER_FROM_SUBACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_TRANSFER_TO_SUBACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_TRANSFER_SOURCE_ID_DUPLICATE_ERROR,

  // 账户余额不足
  ACCOUNT_TRANSFER_BALANCE_INSUFFICIENT_ERROR,

  // 负账户余额溢出
  ACCOUNT_TRANSFER_BALANCE_OVERFLOW_ERROR,

  ACCOUNT_TRANSFER_ORDER_ID_NULL_OR_EMPTY_ERROR,

  ACCOUNT_TRANSFER_ORDER_ID_FORMAT_ERROR,

  // 账户类型为：`%s` 和用户id：`%s` 的记录不存在
  ACCOUNT_GET_ACCOUNTS_INEXISTENT_ERROR,

  // 冻结
  // 账户id：`%s` 和用户id：`%s` 的记录不存在
  ACCOUNT_FROZEN_ACCOUNT_INEXISTENT_ERROR,

  // 用户账户不是交易账户
  ACCOUNT_FROZEN_ACCOUNT_TYPE_UNSUPPORT_ERROR,

  // 交易子账户不存在
  ACCOUNT_FROZEN_TRADE_SUBACCOUNT_INEXISTENT_ERROR,

  // 冻结子账户不存在
  ACCOUNT_FROZEN_FROZEN_SUBACCOUNT_INEXISTENT_ERROR,

  // 订单 `%s`，冻结类型为 `%s` 的操作重复
  ACCOUNT_FROZEN_SOURCE_ID_DUPLICATE_ERROR,

  // 冻结操作类型不支持：`%s`
  ACCOUNT_FROZEN_SOURCE_TYPE_UNSUPPORT_ERROR,

  // 余额不足，剩余：`%s`
  ACCOUNT_FROZEN_BALANCE_INSUFFICIENT_ERROR,

  // 解冻
  ACCOUNT_UNFROZEN_ACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_UNFROZEN_ACCOUNT_TYPE_UNSUPPORT_ERROR,

  ACCOUNT_UNFROZEN_TRADE_SUBACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_UNFROZEN_FROZEN_SUBACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_UNFROZEN_SOURCE_ID_DUPLICATE_ERROR,

  ACCOUNT_UNFROZEN_SOURCE_TYPE_UNSUPPORT_ERROR,

  ACCOUNT_UNFROZEN_BALANCE_INSUFFICIENT_ERROR,

  ACCOUNT_UNFROZEN_FROZEN_ACTION_ERROR,

  // 系统出账
  ACCOUNT_SYSTEMOUT_ACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_SYSTEMOUT_ACCOUNT_TYPE_UNSUPPORT_ERROR,

  ACCOUNT_SYSTEMOUT_SYSTEM_SUBACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_SYSTEMOUT_SOURCE_ID_DUPLICATE_ERROR,

  ACCOUNT_SYSTEMOUT_SOURCE_TYPE_UNSUPPORT_ERROR,

  ACCOUNT_SYSTEMOUT_TRANSFER_ACTION_ERROR,

  ACCOUNT_SYSTEMOUT_BALANCE_INSUFFICIENT_ERROR,

  // 获取用户资产
  // 账户id `%s` 和 用户id `%s` 不匹配
  ACCOUNT_GET_BALANCE_ACCOUNT_INEXISTENT_ERROR,

  // 获取账户动作
  ACCOUNT_GET_ACTION_ACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_GET_ACTION_SOURCE_TYPE_UNSUPPORT_ERROR,

  // 获取账户流水
  ACCOUNT_GET_ACCOUNT_HISTORY_ACCOUNT_INEXISTENT_ERROR,

  ACCOUNT_GET_ACCOUNT_HISTORY_BEGIN_DATE_ERROR,

  ACCOUNT_GET_ACCOUNT_HISTORY_END_DATE_ERROR,

  ACCOUNT_GET_ACCOUNT_HISTORY_TYPE_ERROR,

  // 用户 `%s` 的交易子账户不存在
  ACCOUNT_GET_TRADE_ACCOUNT_NOT_EXIST,

  //web传入的account id `%s` 和系统中的account id 不一致。以后优化api不需要从web传入account id
  ACCOUNT_PLACE_ORDER_ACCOUNT_ID_INCONSISTENT,

  ACCOUNT_TRANSFER_BANNED_BY_BLACKLIST,

  // 用户 `%s` 的 `%s` 账户不存在
  ACCOUNT_INEXISTENT,

  ACCOUNT_HAS_DEBT,
  ;


  public final String errCode;

  AccountErrorEnum() {
    this.errCode = CaseFormat.UPPER_UNDERSCORE.converterTo(CaseFormat.LOWER_HYPHEN).convert(name());
  }

  @Override
  public String getErrCode() {
    return this.errCode;
  }

}
